---
title: "Teaching"
description: |
---
## Current teaching

* **Environmental Economics (2025-), M1 AID, Université Paris-Dauphine - PSL,**
co-taught with Romain Plassard. 

* **PhD Topic (2025), Université Paris-Dauphine - PSL.**
Weather and Climate Projections Data for Economics: An Introduction. [**Slides**](phdtopic/Slides.html), and [**Source Materials**](https://github.com/loichy/PhDTopic_ClimateData.git)

* **Panel data econometrics applied to environmental and agricultural economics (2023-), M1 AID, Université Paris-Dauphine - PSL. **
[**Link to syllabus**](https://www.dropbox.com/scl/fi/5n7xt18fcxx9dxe8zsqem/Syllabus_Panel.pdf?rlkey=sfekfoas1grzfzus5y6ikdmrr&dl=0)

* **Macroeconomics of the environmental transition (2023-), Sustainability Science Program, 2nd year, PSL.** [**Link to syllabus**](https://www.dropbox.com/scl/fi/5n7xt18fcxx9dxe8zsqem/Syllabus_Panel.pdf?rlkey=sfekfoas1grzfzus5y6ikdmrr&dl=0) and 
[**link to tutorial program**](https://www.dropbox.com/scl/fi/pgja1ypj5jc1na2counmf/Tutorial_instructions.pdf?rlkey=3za4n4d5n7pxzse8tg6b0194w&dl=0)

* **Econometrics (2022-), [L3 EID-EIF](https://dauphine.psl.eu/en/training/bachelors-degrees/bachelors-degree-in-applied-economics/bachelors-year-3-international-economics-and-development), Université Paris-Dauphine - PSL.**
<!-- Linear econometrics and ordinary least squares estimator. -->

## Past teaching
* Micro-econometrics (2022-2024), M1 AID, Université Pars-Dauphine
<!-- Teaching assistant for Philippe De Vreyer, in the first year of the [Master AID](https://dauphine.psl.eu/en/training/masters-degrees/international-affairs-and-development). -->

* Advanced econometrics (2021), M1 Master of Economics, Université Paris-Saclay
<!-- Teaching assistant for Hugo Molina, Julien Monardo and Margherita Comola in the first year of the [Master of Economics](https://www.universite-paris-saclay.fr/formation/master/economie/m1-economics#programme). [Link to syllabus](https://www.dropbox.com/s/h7g93zrn1c74s5s/TutorialsProgram.pdf?dl=0). -->
<!-- Practical econometric classes on the basic techniques of non-linear econometrics (including nonlinear least squares, maximum likelihood estimator, discrete choice models, sample selection models) and recent developments in the microeconomic analysis of impact evaluation (including randomized controlled experiments, instrumental variables, matching methods, regression discontinuity and difference-in-differences).  -->

* Econometrics (2017-2021), L3 Economie, ENS Paris-Saclay
<!-- Teaching assistant for Jean-Christophe Tavanti in the Social Science Department at [ENS Paris-Saclay ](https://ens-paris-saclay.fr/en/education/departments/human-and-social-sciences-shs-department).  [Link to problem sets](https://www.dropbox.com/s/0eyha8ubr7fxaot/brochure_tds.pdf?dl=0). [Link to syllabus](https://www.dropbox.com/s/ixu8w4q1g5a590y/prog_TDs_R.pdf?dl=0). -->
<!-- Linear econometrics and ordinary least squares estimator (algebraic properties, geometric properties, and inferential properties). Practical classes, to train students practice of econometrics using R and STATA, supervising a short piece of research in data analysis/econometrics. -->

* Bootcamps (2021), M1 Master of Economics, Université Paris-Saclay

* Microeconomics (2017-2021), L3 Economie, ENS Paris-Saclay

* Economie publique (2016), L3 Economie, Université Paris-Descartes

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

