name: Sync Slides from Private Repo

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  sync_slides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Website Repo
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SLIDES_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Private Slides Repo
        run: |
          git clone --depth 1 git@github.com:loichy/EconomieNature_Slides.git slides-temp

      - name: Copy Slides to Public Repo
        run: |
          mkdir -p slides
          cp slides-temp/Theme1_Slides.html slides/ 
          cp -r slides-temp/css slides/      
          cp -r slides-temp/img slides/
          cp -r slides-temp/libs slides/
          cp slides-temp/xaringan-themer.css slides/
          rm -rf slides-temp

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add slides/slides.html
          git commit -m "Sync latest slides from private repo" || echo "No changes to commit"
          git push origin main
